spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hit-community-database.cwkkcwzvgppa.ap-northeast-2.rds.amazonaws.com:3306/Hit_Community_RDS
    username: admin
    password: Yun970804*
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect=org:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  data:
    redis:
      host: ec2-3-36-128-22.ap-northeast-2.compute.amazonaws.com
      port: 6379
  sql:
    init:
      mode: always
  mail:
    username: sunnamgung8
    password: yun8824
aws:
  ses:
    accessKey: AKIAQANEBH6TO7BUI76L
    secretKey: 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
